import {
  MatButtonModule,
  MatCheckboxModule,
  MatCardModule,
  MatTabsModule,
  MatStepperModule,
  MatFormFieldModule,
  MatInputModule,
  MatGridListModule,
  MatRadioModule,
  MatSelectModule,
  MatTooltipModule,
  MatDividerModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatExpansionModule,
  MatProgressSpinnerModule,
  MatIconModule,
  MatListModule,
  MatChipsModule,
  MatMenuModule,
  MatProgressBarModule
} from '@angular/material';
import { NgModule } from '@angular/core';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatCardModule,
    MatTabsModule,
    MatStepperModule,
    MatFormFieldModule,
    MatInputModule,
    MatGridListModule,
    MatRadioModule,
    MatSelectModule,
    MatTooltipModule,
    MatDividerModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatMenuModule,
    MatProgressBarModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatCardModule,
    MatTabsModule,
    MatStepperModule,
    MatFormFieldModule,
    MatInputModule,
    MatGridListModule,
    MatRadioModule,
    MatSelectModule,
    MatTooltipModule,
    MatDividerModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatIconModule,
    MatListModule,
    MatChipsModule,
    MatMenuModule,
    MatProgressBarModule
  ],
  providers: [MatDatepickerModule]
})
export class MaterialModule {}
